modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/CapabilityProxy/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/capabilityproxy"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="capabilityproxy"
version="${file.jarVersion}"
displayName="CapabilityProxy"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/capabilityproxy.json"
description='''
Access block capabilities from multiple sides.
'''
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.capabilityproxy]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.capabilityproxy]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.capabilityproxy]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,]"
    ordering="NONE"
    side="BOTH"
