modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/CyclopsMC/CapabilityProxy/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/capabilityproxy"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="capabilityproxy"
version="${file.jarVersion}"
displayName="CapabilityProxy"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/capabilityproxy.json"
description='''
Access block capabilities from multiple sides.
'''
[[dependencies.capabilityproxy]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.18.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.capabilityproxy]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.capabilityproxy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,]"
    ordering="NONE"
    side="BOTH"
